### ISSUE TITLE
worksheet redirects to home page when not logged in

### ISSUE THREAD

**Issue by ArdenKirkland** [minorg/dressdiscover#319]
related to #315?

**Comment by minorg** [comment]
The issue is that the current user is configured to use Google Sheets. Querying for the sheets throws an auth exception, which per GenericErrorHandler, redirects to Hrefs.home. The idea was that if you have configured to use sheets then we should not allow you to use local storage accidentally, so you would have to log in and reconfigure to use local storage.

That is probably OK, but we need to show a modal saying that you need to log in to use Google Sheets. Alternatively (another choice), flush the current user if they want to proceed with local storage.

**Comment by minorg** [comment]
The modal specified above should be the general path if there is a 401 or AuthorizationException, rather than simply redirecting. The modal should be static / not allow you to escape it.

**Comment by minorg** [comment]
I implemented the fix above. I tested it by inducing the error. I can't test it under real conditions easily.
